//
//  Images.swift
//  FunWithFlags
//
//  Created by Paul Dinu on 14.05.2023.
//

import SwiftUI

func resize(image: NSImage) -> NSImage {
    let ratio = image.size.height / image.size.width
    image.size.height=18
    image.size.width=18 / ratio
    return image
}

let countryDict: [String:String] = [
    "Afghanistan": "ag.png",
    "Albania" : "al.png",
    "Algeria" : "dz.png",
    "Andorra" : "ad.png",
    "Angola" : "ao.png",
    "Antigua and Barbuda" : "ag.png",
    "Argentina" : "ar.png",
    "Armenia" : "am.png",
    "Australia" : "au.png",
    "Austria" : "at.png",
    "Azerbaijan" : "az.png",
    "Bahamas" : "bs.png",
    "Bahrain" : "bh.png",
    "Bangladesh" : "bd.png",
    "Barbados" : "bb.png",
    "Belarus" : "by.png",
    "Belgium" : "be.png",
    "Belize" : "bz.png",
    "Benin" : "bj.png",
    "Bhutan" : "bt.png",
    "Bolivia" : "bo.png",
    "Bosnia and Herzegovina" : "ba.png",
    "Botswana" : "bw.png",
    "Brazil" : "br.png",
    "Brunei" : "bn.png",
    "Bulgaria" : "bg.png",
    "Burkina Faso" : "bf.png",
    "Burundi" : "bi.png",
    "Cambodia" : "kh.png",
    "Cameroon" : "cm.png",
    "Canada" : "ca.png",
    "Cape Verde" : "cv.png",
    "Central African Republic" : "cf.png",
    "Chad" : "td.png",
    "Chile" : "cl.png",
    "China" : "cn.png",
    "Colombia" : "co.png",
    "Comoros" : "km.png",
    "Republic of Congo" : "cg.png",
    "DR Congo" : "cd.png",
    "Costa Rica" : "cr.png",
    "Côte d'Ivoire" : "ci.png",
    "Croatia" : "hr.png",
    "Cuba" : "cu.png",
    "Cyprus" : "cy.png",
    "Chechia" : "cz.png",
    "Denmark" : "dk.png",
    "Djibouti" : "dj.png",
    "Dominica" : "dm.png",
    "Dominican Republic" : "do.png",
    "Ecuador" : "ec.png",
    "Egypt" : "eg.png",
    "El Salvador" : "sv.png",
    "Equatorial Guinea" : "gq.png",
    "Eritrea" : "er.png",
    "Estonia" : "ee.png",
    "Eswatini" : "sz.png",
    "Ethiopia" : "et.png",
    "Fiji" : "fj.png",
    "Finland" : "fi.png",
    "France" : "fr.png",
    "Gabon" : "ga.png",
    "Gambia" : "gm.png",
    "Georgia" : "ge.png",
    "Germany" : "de.png",
    "Ghana" : "gh.png",
    "Greece" : "gr.png",
    "Grenada" : "gd.png",
    "Guatemala" : "gt.png",
    "Guinea" : "gn.png",
    "Guinea-Bissau" : "gw.png",
    "Guyana" : "gy.png",
    "Haiti" : "ht.png",
    "Honduras" : "hn.png",
    "Hungary" : "hu.png",
    "Iceland" : "is.png",
    "India" : "in.png",
    "Indonesia" : "id.png",
    "Iran" : "ir.png",
    "Iraq" : "iq.png",
    "Ireland" : "ie.png",
    "Israel" : "il.png",
    "Italy" : "it.png",
    "Jamaica" : "jm.png",
    "Japan" : "jp.png",
    "Jordan" : "jo.png",
    "Kazakhstan" : "kz.png",
    "Kenya" : "ke.png",
    "Kiribati" : "ki.png",
    "North Korea" : "kp.png",
    "South Korea" : "kr.png",
    "Kuwait" : "kw.png",
    "Kyrgyzstan" : "kg.png",
    "Laos" : "la.png",
    "Latvia" : "lv.png",
    "Lebanon" : "lb.png",
    "Lesotho" : "ls.png",
    "Liberia" : "lr.png",
    "Libya" : "ly.png",
    "Lichtenstein" : "li.png",
    "Lithuania" : "lt.png",
    "Luxembourg" : "lu.png",
    "Madagascar" : "mg.png",
    "Malawi" : "mw.png",
    "Malaysia" : "lr.png",
    "Maldives" : "mv.png",
    "Mali" : "ml.png",
    "Malta" : "mt.png",
    "Marshall Islands" : "mh.png",
    "Mauritania" : "mr.png",
    "Mauritius" : "mu.png",
    "Mexico" : "mx.png",
    "Micronesia" : "fm.png",
    "Moldova" : "md.png",
    "Monaco" : "mc.png",
    "Mongolia" : "mn.png",
    "Montenegro" : "me.png",
    "Morocco" : "ma.png",
    "Mozambique" : "mz.png",
    "Myamar" : "mm.png",
    "Namibia" : "na.png",
    "Nauru" : "nr.png",
    "Nepal" : "np.png",
    "Netherlands" : "nl.png",
    "New Zealand" : "nz.png",
    "Nicaragua" : "ni.png",
    "Niger" : "ne.png",
    "Nigeria" : "ng.png",
    "North Macedonia" : "mk.png",
    "Norway" : "no.png",
    "Oman" : "om.png",
    "Pakistan" : "pk.png",
    "Palau" : "pw.png",
    "Panama" : "pa.png",
    "Peru" : "pe.png",
    "Philipines" : "ph.png",
    "Poland" : "pl.png",
    "Portugal" : "pt.png",
    "Quatar" : "qa.png",
    "Romania" : "ro.png",
    "Russia" : "ru.png",
    "Rwanda" : "rw.png",
    "Saint Kitts and Nevis" : "kn.png",
    "Saint Lucia" : "lc.png",
    "Saint Vincent and the Grenadines" : "vc.png",
    "Samoa" : "ws.png",
    "San Marino" : "sm.png",
    "São Tomé and Príncipe" : "st.png",
    "Saudi Arabia" : "sa.png",
    "Senegal" : "sn.png",
    "Serbia" : "rs.png",
    "Seychelles" : "sc.png",
    "Sierra Leone" : "sl.png",
    "Singapore" : "sg.png",
    "Slovakia" : "sk.png",
    "Slovenia" : "si.png",
    "Solomon Islands" : "sb.png",
    "Somalia" : "so.png",
    "South Africa" : "za.png",
    "South Sudan" : "ss.png",
    "Spain" : "es.png",
    "Sri Lanka" : "lk.png",
    "Sudan" : "sd.png",
    "Suriname" : "sr.png",
    "Sweden" : "se.png",
    "Switzerland" : "ch.png",
    "Syria" : "sy.png",
    "Tajikistan" : "tj.png",
    "Tanzania" : "tz.png",
    "Thailand" : "th.png",
    "Timor-Leste" : "tl.png",
    "Togo" : "tg.png",
    "Tonga" : "to.png",
    "Trinidad and Tobago" : "tt.png",
    "Tunisia" : "tn.png",
    "Turkey" : "tr.png",
    "Turkmenistan" : "tm.png",
    "Tuvalu" : "tv.png",
    "Uganda" : "ug.png",
    "Ukraine" : "ua.png",
    "United Arab Emirates" : "ae.png",
    "United Kingdom" : "gb.png",
    "United States" : "us.png",
    "Uruguay" : "uy.png",
    "Uzbekistan" : "uz.png",
    "Vanuatu" : "vu.png",
    "Venezuela" : "ve.png",
    "Vietnam" : "vn.png",
    "Yemen" : "ye.png",
    "Zamibia" : "zm.png",
    "Zimbabwe" : "zw.png"
    ]

let orgDict: [String:String] = [
    "EU" : "eu.png",
    "NATO" : "nato.png",
    "UN" : "un.png"
    ]
